[package]
name = "kernel-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"
lto = true
opt-level = "z"
codegen-units = 1

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
codegen-units = 1

[dependencies]
